project:
  type: website
  output-dir: docs

website:
  title: "Alex Wong"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: experience.qmd
        text: Experience
      - href: projects.qmd
        text: Data Projects
      # - href: blog.qmd
      #   text: Blog
  page-footer: "© 2025 Alex Wong"
  

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



